language: python
python:
  - "2.6"
  - "2.7"
# install native packages
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libevent1-dev
 
 
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests
